Here's how you build dfhack!

First, there is one dependency:
  cmake - it's the build system

building the library is simple. Enter the build folder, run 'cmake ..' and 'make'. Like this:
  cd build
  cmake ..
  make

This will build the library and its tools and place them in /output.

You can also use a cmake-friendly IDE like KDevelop 4.

Have fun.