Here's how you build dfhack!

First, there are some dependencies:
  cmake - it's the build system
  zlib - you should have zlib installed

building the library is simple. Enter the build folder and invoke these commands:
  cmake ..
  make

This will build the library and its tools and place them in /output.

Have fun.